name: Build Fritzing on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update Chocolatey
        run: choco upgrade chocolatey -y

      - name: Install Build Dependencies
        run: |
          choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional" -y
          choco install qt5-lts --version=5.15.2 -y
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install python -y

      - name: Cache CMake & Qt Downloads
        uses: actions/cache@v3
        with:
          path: |
            C:\ProgramData\chocolatey\lib\cmake\tools\cmake-*\share\cmake-*
            C:\tools\qt5*
          key: ${{ runner.os }}-fritzing-build-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Setup Environment (PowerShell)
        shell: pwsh
        run: |
          $qtBin = 'C:\Program Files\Qt\5.15.2\msvc2019_64\bin'
          $Env:PATH = "$qtBin;$Env:PATH"
          $Env:CMAKE_GENERATOR = 'Ninja'

      # ### NEU: FREEWING-JP Build-Skript klonen ###
      - name: Klone Build-Skript von FREEWING-JP
        run: git clone https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script.git build-scripts

      - name: Run FREEWING-JP Windows Build Script
        shell: pwsh
        working-directory: build-scripts
        run: .\00_Execute_Script.bat --non-interactive

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: fritzing-windows-exe
          path: |
            build\bin\Fritzing.exe
            build\bin\*.dll

      - name: Upload Installer/ZIP
        uses: actions/upload-artifact@v4
        with:
          name: fritzing-windows-installer
          path: |
            build\Fritzing-*.zip
            build\Fritzing-Setup-*.exe
